
  
  
  server:
    port: 8082
  spring:
  #  zipkin:
  #    base-url: http://localhost:9411/
    h2:
      console:
        enabled: true
    application:
      name: PAYMENT-SERVICE
  logging:
    file: C:\Users\mudit_mangal\Desktop\orderservice.log